# Server Configuration
server:
  port: 9000

# Spring Application
spring:
  application:
    name: oauth2-authorization-server

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Logging
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG